# Site settings
title: Seog Blog
SEOTitle: goesnow | Seog Blog
header-img: img/home-bg.jpg
email: goesnow831@gmail.com
description: "Web Application Engineer | Web & Mobile Lover，Software Engineer | Wonseog's study log。"
keyword: "Frontend, Web, Blog, Typescript, Javascript, Python"
url: "https://leon-dunamu.github.io" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
github_username: "leon-dunamu"
facebook_username: profile.php?id=100004723567545
linkedin_username: wonseog-choi-78a237207

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: goesnow
discus-identifier: goesnow # add your discus identifier

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
# ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
# ga_domain: huangxuan.me

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "Kyung-Hee Univ. <br> Web Front-end Engineer in Dunamu"
sidebar-avatar: /img/profile/seog.png # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false
# Friends
# friends: [
#     {
#     #     title: "Su",
#     #     href: "http://su.gallery/"
#     # },{
#         title: "乱序（Midare）",
#         href: "http://mida.re/"
#     },{
#         title: "Sherry Woo",
#         href: "https://sherrywoo.me/"
#     },{
#         title: "Kun Qian",
#         href: "http://kunq.me"
#     },{
#         title: "Ebn Zhang",
#         href: "http://ebnbin.com/"
#     },{
#         title: "SmdCn",
#         href: "http://blog.smdcn.net"
#     },{
#         title: "JiyinYiyong",
#         href: "http://tiye.me/"
#     },{
#         title: "DHong Say",
#         href: "http://dhong.co"
#     },{
#         title: "尹峰以为",
#         href: "http://ingf.github.io/"
#     }
# ]
